version: '3.8'

services:
  php:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - postgres

  node:
    build: ./node
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: votes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
